version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    reviewers:
      - "timwarner"
    assignees:
      - "timwarner"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
